using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ZNS.EliteTracker.Models.Documents
{
    public enum CommodityType
    {
        Explosives = 1,
        Hydrogen_Fuels = 2,
        Mineral_Oil = 3,
        Pesticides = 4,
        Clothing = 5,
        Consumer_Tech = 6,
        Domestic_Appliances = 7,
        Algae = 8,
        Animal_Meat = 9,
        Coffee = 10,
        Fish = 11,
        Food_Cartridges = 12,
        Fruit_and_Vegetables = 13,
        Grain = 14,
        Synthetic_Meat = 15,
        Tea = 16,
        Polymers = 17,
        Semiconductors = 18,
        Superconductors = 19,
        Beer = 20,
        Liquor = 21,
        Narcotics = 22,
        Tobacco = 23,
        Wine = 24,
        Atmosphereic_Processors = 25,
        Crop_Harvesters = 26,
        Marine_Equipment = 27,
        Microbial_Furnaces = 28,
        Mineral_Extractors = 29,
        Power_Generators = 30,
        Water_Purifiers = 31,
        Agri_Medicines = 32,
        Basic_Medicines = 33,
        Combat_Stabilisers = 34,
        Performance_Enhancers = 35,
        Progenitor_Cells = 36,
        Aluminium = 37,
        Beryllium = 38,
        Cobalt = 39,
        Copper = 40,
        Gallium = 41,
        Gold = 42,
        Indium = 43,
        Lithium = 44,
        Palladium = 45,
        Platinum = 46,
        Silver = 47,
        Tantalum = 48,
        Titanium = 49,
        Uranium = 50,
        Bauxite = 51,
        Bertrandite = 52,
        Coltan = 53,
        Gallite = 54,
        Indite = 55,
        Lepidolite = 56,
        Rutile = 57,
        Uraninite = 58,
        Imperial_Slaves = 59,
        Slaves = 60,
        Advanced_Catalysers = 61,
        Animal_Monitors = 62,
        Aquaponic_Systems = 63,
        Auto_Fabricators = 64,
        Bioreducing_Lichen = 65,
        Computer_Components = 66,
        HE_Suits = 67,
        Land_Enrich_Sys = 68,
        Resonating_Separators = 69,
        Robotics = 70,
        Leather = 71,
        Natural_Fabrics = 72,
        Synthetic_Fabrics = 73,
        Biowaste = 74,
        Chemical_Waste = 75,
        Scrap = 76,
        Toxic_Waste = 77,
        Battle_Weapons = 78,
        Non_lethal_Weapons = 79,
        Personal_Armour = 80,
        Personal_Weapons = 81,
        Reactive_Armour = 82
    }
}